name: Hello World Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions! helllo world123"

      - name: Print date
        run: date

